build: off

os: unstable

branches:
  only:
    - master

skip_tags: true

environment:
  nodejs_version: "8.12.0"

cache:
  - node_modules -> package.json
  - "%LOCALAPPDATA%\\Yarn"

install:
  - ps: Install-Product node $env:nodejs_version
  - git submodule update --init
  - yarn

test_script:
  - SET NODE_ENV=production
  - yarn run compile
